version: '3.8'

services:
  backend:
    image:
      sep4backendregistry.azurecr.io/backend:v1
    ports:
      - "7128:7128"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7128
  
  frontend:
    image:
      sep4frontend2024.azurecr.io/green-house-dev:v1
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:7128
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend