version: '3.8'

services:
  proxy:
    image:
      sep4backendregistry.azurecr.io/proxy:latest
    ports:
      - "80"
  backend:
    image:
      sep4backendregistry.azurecr.io/backend:v1
    volumes:
      - ${WEBAPP_STORAGE_HOME}:/Database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7128
      - DBDIR=/Database