# .github/workflows/main.yml

name: CI on Main

on:
  push:
    branches:
      - main

jobs:
  unit_test:
    uses: mtezxx/greenhouse-backend-cloud/.github/workflows/unit_test.yml
    secrets: inherit
