# .github/workflows/main.yml

name: CI on Main

on:
  push:
    branches:
      - main

jobs:
  unit_test:
    uses: ./.github/workflows/unit_test.yaml
    with:
    # specify inputs if any
    secrets: inherit
