# .github/workflows/main.yml

name: CI on Main

on:
  push:
    branches:
      - main

jobs:
  unit_test:
    uses: mtezxx/greenhouse-backend-cloud/.github/workflows/unit_test.yml@main  # Use the unit_test.yml workflow
    secrets:
      EMAIL: ${{ secrets.EMAIL }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
