name: Unit Test

on:
  workflow_call:
    secrets:
      EMAIL:
        required: true
      EMAIL_PASSWORD:
        required: true

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ secrets.EMAIL }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        run: dotnet test